name: autostore
display_name: Theme Auto Parts
dependencies:
  modules:
    - pp_newproducts
    - pp_specials
    - pp_bestsellers
    - pp_featuredproducts
    - htmlbanners1
    - htmlbanners2
    - htmlbanners5
    - htmlbanners6
    - htmlbanners7
    - htmlbanners8
    - htmlbanners9
    - htmlbanners10
    - blockmanufactureri
    - blockfacebook
    - fancyboxthumb
    - productsfromcategory1
    - productsfromcategory2
    - productsfromcategory3
    - productsfromcategory4
    - customtabs
version: 1.4.8
theme_key: c5e895510f3671becbb3250f61e20316
author:
  name: "Prestahero Team"
  email: "contact@prestashop.com"
  url: "https://addons.prestashop.com/en/2_community-developer?contributor=539897"

meta:
  compatibility:
      from: 1.7.0.0
      to: ~

  available_layouts:
    layout-full-width:
      name: Full Width
      description: No side columns, ideal for distraction-free pages such as product pages.
    layout-both-columns:
      name: Three Columns
      description: One large central column and 2 side columns.
    layout-left-column:
      name: Two Columns, small left column
      description: Two columns with a small left column
    layout-right-column:
      name: Two Columns, small right column
      description: Two columns with a small right column

assets:
  js:
    index:
      - id: owl-carousel
        path: assets/js/owl.carousel.min.js
        priority: 55
      - id: wow-library
        path: assets/js/wow.js
        priority: 60
      - id: carousels
        path: assets/js/carousels.js
        priority: 65
      - id: index-extra-scripts
        path: assets/js/index.js
        priority: 70
    category:
      - id: owl-carousel
        path: assets/js/owl.carousel.min.js
        priority: 55
    product:
      - id: owl-carousel
        path: assets/js/owl.carousel.min.js
        priority: 55
      - id: carousels
        path: assets/js/carousels.js
        priority: 60
    order-confirmation:
      - id: owl-carousel
        path: assets/js/owl.carousel.min.js
        priority: 55
      - id: carousels
        path: assets/js/carousels.js
        priority: 60
    cart:
      - id: owl-carousel
        path: assets/js/owl.carousel.min.js
        priority: 55
      - id: carousels
        path: assets/js/carousels.js
        priority: 60


global_settings:
  configuration:
    PS_IMAGE_QUALITY: png
    NEW_PRODUCTS_NBR: 4
    PS_BLOCK_BESTSELLERS_TO_DISPLAY: 4
    BLOCKSPECIALS_SPECIALS_NBR: 4
    MANUFACTURERI_DISPLAY_TEXT_NB: 15
    MANUFACTURERI_DISPLAY_TEXT: true
    PPBESTSELLERS_TO_DISPLAY: 8
    PPBESTSELLERS_CAROUSEL: 0
    PPBESTSELLERS_AUTOPLAY_SLI: 1
    PPBESTSELLERS_SPEED_SLI: 5000
    PPBESTSELLERS_PAG_SLI: 0
    PPBESTSELLERS_ARROWS_SLI: 1
    PPBESTSELLERS_LOOP_SLI: 0
    PPBESTSELLERS_COL: 4
    PPBESTSELLERS_COL_1200: 4
    PPBESTSELLERS_COL_992: 3
    PPBESTSELLERS_COL_769: 3
    PPBESTSELLERS_COL_576: 2
    PPBESTSELLERS_ROWS_SLI: 1
    PPBESTSELLERS_TABS: 1
    PPFEATURED_NBR: 8
    PPFEATURED_CAT: 2
    PPFEATURED_RANDOMIZE: 0
    PPFEATURED_CAROUSEL: 0
    PPFEATURED_AUTOPLAY_SLI: 1
    PPFEATURED_SPEED_SLI: 5000
    PPFEATURED_PAG_SLI: 0
    PPFEATURED_ARROWS_SLI: 1
    PPFEATURED_LOOP_SLI: 0
    PPFEATURED_COL: 4
    PPFEATURED_COL_1200: 4
    PPFEATURED_COL_992: 3
    PPFEATURED_COL_769: 3
    PPFEATURED_COL_576: 2
    PPFEATURED_ROWS_SLI: 1
    PPFEATURED_TABS: 1
    PPNEW_NBR: 8
    PPNEW_CAROUSEL: 0
    PPNEW_AUTOPLAY_SLI: 1
    PPNEW_SPEED_SLI: 5000
    PPNEW_PAG_SLI: 0
    PPNEW_ARROWS_SLI: 1
    PPNEW_LOOP_SLI: 0
    PPNEW_COL: 4
    PPNEW_COL_1200: 4
    PPNEW_COL_992: 3
    PPNEW_COL_769: 3
    PPNEW_COL_576: 2
    PPNEW_ROWS_SLI: 1
    PPNEW_TABS: 1
    PPONSALE_NBR: 8
    PPONSALE_CAROUSEL: 0
    PPONSALE_AUTOPLAY_SLI: 1
    PPONSALE_SPEED_SLI: 5000
    PPONSALE_PAG_SLI: 0
    PPONSALE_ARROWS_SLI: 1
    PPONSALE_LOOP_SLI: 0
    PPONSALE_COL: 4
    PPONSALE_COL_1200: 4
    PPONSALE_COL_992: 3
    PPONSALE_COL_769: 3
    PPONSALE_COL_576: 2
    PPONSALE_ROWS_SLI: 1
    PPONSALE_TABS: 1
  modules:
   to_install:
    - ps_newproducts
    - ps_bestsellers
    - ps_specials
    - ps_categoryproducts
    - productcomments
    - fancyboxthumb
   to_enable:
      - ps_linklist
      - ps_newproducts
      - ps_bestsellers
      - ps_specials
      - ps_categoryproducts
      - fancyboxthumb
   to_disable:
     - welcome
     - gamification
     - ps_imageslider
  hooks:
    modules_to_hook:
      displayAfterBodyOpeningTag:
        - blockreassurance
      displayNavFullWidth:
        - blockreassurance
      displayTopColumn:
        - htmlbanners9
        - htmlbanners1
      displayNav1:
        - ps_languageselector
        - ps_currencyselector
      displayNav2:
        - ps_searchbar
        - ps_shoppingcart
        - ps_contactinfo
        - ps_customersignin
      displayTop:
        - htmlbanners6
        - ps_mainmenu
      displayHomeTab:
        - pp_featuredproducts
        - pp_bestsellers
        - pp_newproducts
        - pp_specials
      displayHomeTabContent:
        - pp_featuredproducts
        - pp_bestsellers
        - pp_newproducts
        - pp_specials
      displayHome:
        - htmlbanners2
        - htmlbanners10
        - htmlbanners5
        - blockmanufactureri
        - ps_customtext
        - ps_banner
      displayHomeCustom:
        - productsfromcategory1
        - productsfromcategory2
        - productsfromcategory3
        - productsfromcategory4
      displayFooterBefore:
        - ps_contactinfo
        - ps_emailsubscription
      displayFooter:
        - blockfacebook
        - ps_linklist
        - blockwishlist
      displayFooterAfter:
        - htmlbanners7
        - ps_socialfollow
      displayLeftColumn:
        - ps_categorytree
        - ps_facetedsearch
        - ps_newproducts
        - ps_bestsellers
        - ps_specials
      displayLeftColumnProduct:
        - ps_categorytree
        - ps_newproducts
        - ps_bestsellers
        - ps_specials
      displaySearch:
        - ps_searchbar
      displayProductAdditionalInfo:
        - ps_sharebuttons
        - productcomments
      displayReassurance:
        - blockreassurance
      displayOrderConfirmation2:
        - ps_featuredproducts
      displayCrossSellingShoppingCart:
        - ps_featuredproducts
      displayFooterProduct:
        - productcomments
        - ps_categoryproducts
      displayHtmlContent4:
        - htmlbanners8
      productTab:
        - customtabs
      productTabContent:
        - customtabs
      displayProductListReviews:
        - productcomments
      displayAdminCustomers:
        - blockwishlist
      displayCustomerAccount:
        - blockwishlist
        - psgdpr
      displayMyAccountBlock:
        - blockwishlist
      displayProductActions:
        - blockwishlist
      displayGDPRConsent:
        - psgdpr

  image_types:
    cart_default:
      width: 125
      height: 125
      scope: [products]
    small_default:
      width: 150
      height: 150
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 380
      height: 272
      scope: [products, manufacturers, suppliers]
    home_default:
      width: 270
      height: 270
      scope: [products]
    large_default:
      width: 650
      height: 650
      scope: [products, manufacturers, suppliers]
    category_default:
      width: 1170
      height: 420
      scope: [categories]
    stores_default:
      width: 170
      height: 115
      scope: [stores]
    manufacturer_default:
      width: 170
      height: 73
      scope: [manufacturers]

theme_settings:
  default_layout: layout-full-width
  layouts:
    category: layout-left-column
    best-sales: layout-left-column
    new-products: layout-left-column
    prices-drop: layout-left-column
    contact: layout-left-column
    search: layout-left-column
    supplier: layout-left-column
    manufacturer: layout-left-column
